name: Generate Image in Artifacts

on:
    workflow_dispatch:
        inputs:
            date:
                description: 'The ISO date of the event'
                required: true
            title:
                description: 'The main title of the event'
                required: true
            secondaryTitle:
                description: 'The secondary title of the event'
                default: ''

jobs:
    generate:
        name: Setup project and generate image
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '20.x'
            - name: Disable AppArmor
              run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns
            - run: npm install
            - run: node index.js --date="${{ github.event.inputs.date }}" --title="${{ github.event.inputs.title }}" --secondaryTitle="${{ github.event.inputs.secondaryTitle }}"
            - name: Archive generated image
              uses: actions/upload-artifact@v3
              with:
                name: meetup-image
                path: image.jpg
